name: weather_app
description: "A simple weather app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  http: ^1.2.0
  intl: any
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/weather/videos/
    - assets/weather/icons/day/
    - assets/weather/icons/night/

  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
      
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf

    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf

    - family: Gilroy-Black
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Black.ttf
        
        
        
          
