name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
      
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf

    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf

    - family: Gilroy-Black
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Black.ttf
        
        
        
          
