name: Main

on:
  push:
    branches:
      - deployment-process

jobs:
  version-check:
    runs-on: macos-latest
    outputs:
      current_version: ${{ steps.extract_version.outputs.current_version }}
      previous_version: ${{ steps.get_previous_version.outputs.previous_version }}
      build_number: ${{ steps.get_build_number.outputs.build_number }}
      version_changed: ${{ steps.version_check.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache previous version and build number
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            previous_version.txt
            build_number.txt
          key: version-cache

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 1)
          build_number=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 2)
          echo "current_version=$version" >> $GITHUB_ENV
          echo "build_number=$build_number" >> $GITHUB_ENV
          echo "current_version=$version" >> $GITHUB_OUTPUT
          echo "build_number=$build_number" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: get_previous_version
        run: |
          if [ -f previous_version.txt ]; then
            previous_version=$(cat previous_version.txt)
          else
            previous_version="0.0.0"
          fi
          echo "previous_version=$previous_version" >> $GITHUB_ENV
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

      - name: Get new build number
        id: get_build_number
        run: |
          if [ -f build_number.txt ]; then
            build_number=$(cat build_number.txt)
            build_number=$((build_number + 1))
          else
            build_number=1
          fi
          echo "build_number=$build_number" >> $GITHUB_ENV
          echo "build_number=$build_number" >> $GITHUB_OUTPUT
          echo $build_number > build_number.txt

      - name: Save current version
        run: echo "${{ steps.extract_version.outputs.current_version }}" > previous_version.txt

      - name: Check if version changed
        id: version_check
        run: |
          if [ "${{ steps.extract_version.outputs.current_version }}" != "${{ steps.get_previous_version.outputs.previous_version }}" ]; then
            echo "version_changed=true" >> $GITHUB_ENV
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_ENV
            echo "version_changed=false" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: version_artifacts
          path: |
            previous_version.txt
            build_number.txt

  deploy-android:
    runs-on: ubuntu-22.04
    needs: version-check
    if: ${{ needs.version-check.outputs.version_changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: 'stable'
          cache: true

      - name: Create .env file
        run: |
          touch .env
          echo WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} >> .env
          cat .env

      - name: Get Flutter Project dependencies
        run: flutter pub get
       
      - name: Build release app bundle
        run: flutter build appbundle

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1   
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}         
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}             
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload Signed App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: signed-app-bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Upload to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1.0.18  
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
          packageName: com.halfseed.climature     
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}        
          mappingFile: ./build/app/outputs/mapping/release/mapping.txt
          track: internal
            
  deploy-ios:
    runs-on: macos-latest
    needs: version-check
    if: ${{ needs.version-check.outputs.version_changed == 'true' }}
    env:
      APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      DIST_CERTIFICATE: ${{ secrets.DIST_CERTIFICATE }}
      DIST_CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERTIFICATE_PASSWORD }}
      DIST_PROFILE: ${{ secrets.DIST_PROFILE }}
      APP_STORE_APP_ID: ${{ vars.APP_STORE_APP_ID }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: 'stable'
          cache: true

      - name: Install Codemagic CLI tools
        run: pip install codemagic-cli-tools

      - name: Set up keychain
        run: keychain initialize

      - name: Set up Provisioning profiles
        run: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${DIST_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"

      - name: Set up signing certificate
        run: |
          echo $DIST_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $DIST_CERTIFICATE_PASSWORD

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Create .env file
        run: |
          touch .env
          echo WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} >> .env
          cat .env

      - name: Set version and build number
        run: |
          cd ios
          agvtool new-marketing-version ${{ needs.version-check.outputs.current_version }}
          agvtool new-version -all ${{ needs.version-check.outputs.build_number }}

      - name: Build ipa for distribution
        run: flutter build ipa --release --export-options-plist=$HOME/export_options.plist

      - name: Publish the app to App Store Connect
        run: |
          APP_FILE=$(find $(pwd) -name "*.ipa")
          app-store-connect publish --path "$APP_FILE"
